
import { initializeApp, getApps, getApp } from "firebase/app";
import { getFirestore, collection, addDoc } from "firebase/firestore";
import type { SensorData } from "@/app/ble-connector";

// Your web app's Firebase configuration
// IMPORTANT: This object is generated by Firebase and should not be modified.
const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);

const SENSOR_DATA_COLLECTION = 'sensor_readings';

/**
 * Saves a sensor data reading to Firestore.
 * @param sensorData The sensor data object to save.
 */
export const saveSensorDataToFirestore = async (sensorData: SensorData): Promise<string> => {
  try {
    const docRef = await addDoc(collection(db, SENSOR_DATA_COLLECTION), {
      ...sensorData,
      // Firestore automatically adds a server-side timestamp, which is more reliable.
      // We can add it here if needed, but let's rely on Firestore's for now.
      cloud_timestamp: new Date() 
    });
    console.log("Document written with ID: ", docRef.id);
    return docRef.id;
  } catch (e) {
    console.error("Error adding document: ", e);
    throw new Error("Could not save data to Firestore.");
  }
};
